WhiteLagoon/WhiteLagoon.Web/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;

namespace WhiteLagoon.Web.Controllers
{
    public class BookingController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public BookingController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult FinalizeBooking(int villaId, DateOnly checkInDate, int nights)
        {
            Booking booking = new ()
            {
                VillaId = villaId,
                Villa = this.unitOfWork.Villa.Get(u => u.Id == villaId, includeProperties: "VillaAmenity"),
                CheckInDate = checkInDate,
                Nights = nights,
                CheckOutDate = checkInDate.AddDays(nights)
            };
            return View(booking);
        }
    }
}

WhiteLagoon/WhiteLagoon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/WhiteLagoon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villa</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">Villa Number</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-area="" asp-controller="Amenity" asp-action="Index">Amenity</a>
                                </li>
                            </ul>
                        </li>                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by Tsvetelina
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon/WhiteLagoon.Web/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

WhiteLagoon/WhiteLagoon.Web/Views/Shared/_VillaDetail.cshtml
@model Villa

<div class="row">
    <div class="col-12 col-md-5">
        <img src="@Model.ImageUrl" style="border-radius:10px;" width="100%" />
    </div>
    <div class="col-12 col-md-7">
        <div class="row p-2">
            <div class="col-12">
                <p class="card-title text-warning" style="font-size:xx-large">@Model.Name</p>
                <p class="card-text" style="font-size:large">
                    @Html.Raw(Model.Description)
                </p>
                @if (Model.VillaAmenity != null && Model.VillaAmenity.Count() > 0)
                {
                    <p class="h5 text-white">Villa Amenities</p>
                    <ul>
                        @foreach (var amenity in Model.VillaAmenity)
                        {
                            <li>@amenity.Name</li>
                        }
                    </ul>
                }
            </div>
        </div>
        <div class="row col-12">
            <span class="text-end p-0 pt-3 m-0">
                <span class="float-right">Max Occupancy : @Model.Occupancy adults </span><br />
                <span class="float-right pt-1">Villa Size : @Model.Sqft sqft</span><br />
                <p class="text-warning font-weight-bold pt-1">
                    USD
                    <span style=" #ff6a00">
                        @Model.Price.ToString("c") / night
                    </span>
                </p>
            </span>
        </div>
    </div>
</div>

WhiteLagoon/WhiteLagoon.Web/Views/Shared/_VillaList.cshtml
@model HomeVM


<div id="VillasList">

    <div class="row px-lg-5 m-lg-4 m-sm-0 px-sm-0" style="--bs-gutter-x:0">
        @foreach (var villa in Model.VillaList)
        {
            <div class="p-4 col-md-12 col-lg-6">
                <div class="row" style="border-radius:5px; border: 1px solid #aaa">
                    <div class="col-4 p-2">
                        <img class="d-block w-100" style="border-radius:5px;" src="@villa.ImageUrl">
                    </div>
                    <div class="col-8">
                        <div class="d-flex justify-content-between">
                            <p class="card-title text-warning" style="font-size:xx-large">@villa.Name</p>
                            <div class="pt-2">
                                <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target='#exampleModal-@(villa.Id)'>
                                    Details
                                </button>
                            </div>
                        </div>
                        <p class="card-text">
                            @Html.Raw(villa.Description)
                        </p>
                    </div>
                    <div class="col-12">
                        <div class="row pb-3 pt-2">
                            <div class="col-4">
                                @if (Model.CheckInDate > DateOnly.FromDateTime(DateTime.Now))
                                {
                                    if (villa.isAvailable)
                                    {
                                        <a asp-controller="Booking" asp-action="FinalizeBooking" asp-route-villaId="@villa.Id" asp-route-checkInDate="@Model.CheckInDate" asp-route-nights="@Model.Nights" class="btn btn-success form-control btn-block">
                                            Book
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-outline-danger disabled form-control btn-block">
                                            Sold out
                                        </a>
                                    }
                                }

                            </div>
                            <div class="col-4">
                                <span class="">Max Occupancy : @villa.Occupancy adults </span><br />
                                <span class=" pt-1">Villa Size : @villa.Sqft sqft</span><br />
                            </div>
                            <div class="col-4">
                                <span class="text-warning float-end font-weight-bold pt-1" style="font-size:25px;">
                                    USD
                                    <span style="border-bottom:1px solid #ff6a00">
                                        @villa.Price.ToString("c")
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="modal fade" id="exampleModal-@(villa.Id)" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl" style="border: 1px solid #aaa; border-radius:7px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-3 text-success" id="exampleModalLabel">Villa Details</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body m-0">
                            <partial name="_VillaDetail" model="@villa" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
</div>